[licenses]
unlicensed = "deny"
copyleft = "warn"

default = "deny"

allowed = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "0BSD",
    "ISC",
    "CC0-1.0",
    "Zlib",
    "Unicode-DFS-2016",
]

[sources]
unknown-registry = "deny"
unacceptable = []

default = "allow"